web/Dockerfile

Running this Dockerfile on Fedora 22 throws a "not a directory" error when it reaches "ADD cert/cert.pem /cert". Adding a backslash to the path resolves the issue.

Add trailing backslash to fix "not a directory" error

---

app/Dockerfile

The new stable version is out :)
https://github.com/mattermost/platform/releases/tag/v2.0.0

app: Upgrade Mattermost to 2.0.0

---

db/setup-wale.sh

$PGDATA is set in upstream postgres dockerfile and should be used in
downstream in case the postgres data directory is changed in the future.
This PR depends on #18

Use $PGDATA env var to setup wal-e

---

web/mattermost
web/mattermost-ssl

See #57 and https://github.com/mattermost/platform/issues/3944
Added workarounds to both nginx configs (ssl and no ssl) to grab the correct protocol and pass it in the `X-Forwared-Proto` header.
If this web proxy receives a connection which already has `X-Forwared-Proto` set it will use this, otherwise it will sue default `$scheme` variable.

Fixing web proxy dealing with protocols

---

app/Dockerfile

Updating Dockerfile for Mattermost 3.6.2

---

docker-compose-v1.yml
docker-compose.yml

- db setting is available on db
- app also uses same valiables (eg. MM_USERNAME...)  however there is no hint on compose file.
```bash
#!/bin/bash
config=/mattermost/config/config.json
DB_HOST=${DB_HOST:-db}
DB_PORT_5432_TCP_PORT=${DB_PORT_5432_TCP_PORT:-5432}
MM_USERNAME=${MM_USERNAME:-mmuser}
MM_PASSWORD=${MM_PASSWORD:-mmuser_password}
MM_DBNAME=${MM_DBNAME:-mattermost}
```
app also uses MM_USERNAME, MM_PASSWORD and MM_DBNAME however there is no hint on compose file.  If I change these value on db compose setting, I have to change app too. So I add some hint on docker-compose.yml.

set db setting on app also

---

README.md
app/Dockerfile
app/docker-entry.sh
docker-compose-v1.yml
docker-compose.yml

Config file should be stored in a persistent storage as it is stores the
app status and configuration. It should be independent from container
life cycle and mounted into app container. This commit allows config
location to be changed through CLI. So that when the persistent storage
is mounted, the location can be pointed to the mounted config file.
Also some updates for best practices:
* extracted version numbers in Dockerfile into a environment variable
* Added mattermost/bin to PATH environment variable

Allow config location to be customized from CLI

---

docker-compose-v1.yml
docker-compose.yml

If people use mattermost-docker compose file on their production environment, they may want to maintain  their log.

 add log dir volume option on docker-compose file

---

.gitignore
README.md
app/Dockerfile-enterprise
docker-compose-v1.yml
docker-compose.yml

Since the only difference is mattermost package and  we don't want
to maintain two difference branches, just moved the enterprise version
into a alternative dockerfile

Move enterprise version into this branch

---

db/Dockerfile

libssl-dev is needed to be installed on Ubuntu or the build won't be succeed.

fix build error on Ubuntu 14.04

---

Dockerrun.aws.json
docker-compose.yml

The current Dockerrun.aws.json is about a year old and no longer works. I believe I've fixed the issues and would like to have this committed to the repo.

Fix Dockerrun.aws.json so that it works with the latest docker setup

---

app/Dockerfile
app/Dockerfile-enterprise
app/docker-entry.sh

PR #131 introduced a **big** issue which cause Mattermost app to not be configurable (as described on #136).
It seems that using environment variables to modify the default Mattermost configuration (as described [here](https://docs.mattermost.com/administration/config-settings.html)) is not a really good idea. Instead, Mattermost app should have the following behavior :
- if a `config.json` file already exists (using volumes mount), do not modify configuration. Only override database connection (since it **should** be done by passing environment vars to app container)
- if there is no `config.json` use the default one and change some vars using `jq`
I run test locally and it respect this behavior. Looks good to me.
@xcompass @br00tal

Do not use env variables to override APP conf. (fix #136)

---

docker-compose.yml

In `docker-compose.yml` file, I think it should be better to use `links` instead of `depends_on` by default. It will allow to change services names (like in https://github.com/mattermost/mattermost-docker/issues/142#issuecomment-309374431 ) without breaking containers which hardcode `app` and `db` hostnames.

Use links instead of depends_on

---

app/docker-entry.sh

This allows MySQL users to predefine a custom `MM_SQLSETTINGS_DATASOURCE`, which needed for the database connection. 
In the official [docs](https://docs.mattermost.com/install/install-ubuntu-1604.html#installing-mattermost-server) the following connection „string“ is mentioned for MySQL users: 
```
"mmuser:<mmuser-password>@tcp(<host-name-or-IP>:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
```
Without this change the container forces the Mattermost server to use a Postgres connection, even if the config file defines MySQL.

Only configure database connection if needed

---

README.md
contrib/swarm/docker-stack.yml
docker-swarm.yml
web/docker-entry.sh

Signed-off-by: Pierre DEMAGNY <pdemagny@printoclock.com>

add docker swarm mode support

---

app/Dockerfile

Mattermost `4.3.0` will be released on October 16th.
Changelog is [here](https://docs.mattermost.com/administration/changelog.html?highlight=changelog#release-v4-3-0).

Upgrade to 4.3.0

---

docker-compose.yml

Using links is considered to be a deprecated feature of Docker,
in favor of user-defined networks (see
https://docs.docker.com/engine/userguide/networking/default_network/dockerlinks/).
Since the docker-compose file is in Version 2, a network is
automatically created for the 3 containers, making them accessible to each others with their name directly.

Remove deprecated links in docker-compose file

---

app/Dockerfile

We need to upgrade to 4.0.5 for now. Here is the change log: https://docs.mattermost.com/administration/changelog.html#release-v4-0-5

Add version 4.0.5

---

README.md
docker-compose.yml
web/entrypoint.sh
web/mattermost
web/mattermost-ssl

On #142 issue @JannikZed explained that, because he was using Sloppy.io provider, he had to modify Web container to use a different App hostname.
Because it cost nothing to add this feature, I just add few lines and Web image to allow user to choose (with environment variables) the hostname and port of the app container. Default values stay `app` and `80`, so not a breaking change.
As usual, I appreciate review @xcompass ;)

Allow to customize application host/port on Web container

---

app/entrypoint.sh

* URL Encode the Postgres password, allowing for special characters in the connection string.
This uses Python to do the quoting, which is available in Ubuntu by default. If #208 is being considered, we'll either need to install Python in that or adapt the implementation here.

[FIX] URLEncode PSQL Password

---

web/mattermost-ssl

Fix 404 broken link.
---
There is something I want to confirm.
This fixing and [More Information](https://github.com/mattermost/mattermost-docker#more-information) in README are pointing mattermost docs about ubuntu-**14.04**.
Is it right? should be point ubuntu-**16.04**?

Fix broken link

---

README.md

Updating link about the install instruction for Ubuntu from `14.04` to `16.04`.
Be same as the other page(refs #227).

updating link about install instruction for Ubuntu

---

app/Dockerfile

Release: https://github.com/mattermost/mattermost-server/releases/tag/v4.9.0
Changelog: https://github.com/mattermost/docs/blob/e55503f1633027b67be727eebfe04530eaa67180/source/administration/changelog.md#release-v49

Upgrade mattermost to 4.9.0

---

.travis.yml
README.md
app/Dockerfile
app/entrypoint.sh
contrib/aws/Dockerrun.aws.json
contrib/swarm/docker-stack-traefik.yml
contrib/swarm/docker-stack.yml
docker-compose.yml

Now, volumes settings doesn't include `plugins` directory.
So when recreating containers, all plugins will be removed.
I think that it had better to add `plugins` directory to volumes settings.

Backup plugins directory

---

app/Dockerfile

using the new plugin feature there are two volumes one for the /mattermost/plugin which is for the server side and the /mattermost/client/plugins for the webapp part.

add volume for client/plugins

---

app/Dockerfile

We will start building this Image for both team and enterprise version from master and release branches
to achieve that we need to be able to point to any build we need.

add ability to build your own mm binary

---

app/entrypoint.sh

just realize that this PR https://github.com/mattermost/mattermost-docker/pull/315 checks the variable DB and db exist always we need to check if a config or the MM_SQLSETTINGS_DATASOURCE not set

Remove DB check in the app/entrypoint

---

db/Dockerfile

Because the PostgreSQL user is not always "postgres", do not specify a user to the Healthcheck command. It will also works correctly.

Fix database healthcheck

---

app/Dockerfile

fixes: https://github.com/mattermost/mattermost-docker/issues/328

fix permission in plugin folder

---

contrib/swarm/docker-stack-traefik.yml

Hello,
The traefik command is pretty long. You can use yaml folded style:
- Each line break is replaced by a space.
- The indention in each line will be ignored
- A line break will be inserted at the end.
Which keep the current behaviour

Break traefik command in multiple lines

---

README.md

Jira: https://mattermost.atlassian.net/browse/MM-15327

update readme to add deprecation notice

---

app/Dockerfile

There has been [some issues](https://github.com/scottleedavis/mattermost-plugin-remind/issues/88) with running a plugin that uses time.In(location), where location is loaded by tzdata information.  
http://pouzek.si/blog/go-loadlocation-docker/
This PR adds the tzdata apk to the app container

include timezone for plugins that use location information.

---

MAINTENANCE.md

Hi @jasonblais and @cpanato 
Has I said on pre-release, I'm not maintaining this repository anymore, my last activity was several months ago, I'm not able to dedicate time for Mattermost's docker images anymore.
So I just remove myself from maintainers list.
I let you merge the PR, as I think you should remove my write access on the repository at the same time :)

Remove @pichouk from active maintainers

---

docker-compose.yml

I recently ran into build errors caused by missing proxy configuration. This could be solved by providing the `--build-arg` parameter and setting the needed environment vars.
But this feature was added in the docker-compose file rev. > `2.2`.
If you try to build the images without the `--build-arg` parameter it throws `DNS resolv` and `permission denied` errors in the `db` image. This is caused by the `apk add` command from the underlying alpine image.
> So you have to provide additional build args in environments where the build takes place behind non transparent proxy. The simplest way is to use the `--build-arg` parameter from docker-compose. Otherwise you would have to edit each Dockerfile manually.
So this could fix the build problems for any environment with a proxy.
If you don't …

update docker-compose version

---

docker-compose.yml

- The env variable `MM_SQLSETTINGS_DATASOURCE` exported in `app/entrypoint.sh` isn't kept as an environment variable in the app container after startup. 
- One solution is to manually define it in the `docker-compose.yml` file. This keeps it in the environment, so when the CLI is started sometime later, the correct database connection string is used.
- Totally open to other solutions. 
- I tried to reference the variables (eg, `${MM_USERNAME}`) in the string, but docker-compose isn't set up to do that. One way would be to use an environment file, import it, and then you could reference those variables. Do you want to do that @cpanato?
- This is being felt by customers using 5.12-on, should we update those releases with this?
- [MM-18794](https://mattermost.atlassian.net/browse/MM-18794)

[MM-18794] mattermost command line broken in Docker since the 5.11.1 -> 5.12.0 transition

---

README.md
docker-compose.yml

**Problem:**
For installation of Team Edition, simply commenting out the two lines mentioned in README does not work. Created issue #437 for it.
**Solution:**
After looking at a few blogs and the commit history of the `docker-compose.yml` . I observed that the `context: ` has been deleted by some other PR which was previously present. So I have 
added it back to make team edition deployments work.
**Fixes:**
- Added the context block in `docker-compose.yml`
- Added the subsequent changes in the installation instructions in README.md
Probably wrong docker-compose file syntax #437

Fixes for the smooth deployment of Team edition.

---

app/Dockerfile

Mattermost 5.18.1 was released yesterday, bumping the `Dockerfile` ENV variable so Docker installs can upgrade.
N/A

bump to 5.18.1

---

db/Dockerfile

I tried to use wal-e as mentioned on dockerhub (see https://hub.docker.com/r/mattermost/mattermost-prod-db). To do the base backup I had to do some additional steps (see https://github.com/mattermost/mattermost-docker/issues/346):
- mount a volume into the database docker container (path in the container is /etc/wal-e.d/env) and put all credentials and the s3 prefix to this folder
- exec into the container and create a superuser (Command: CREATE USER postgres SUPERUSER;)
Now it still fails with the message, that the package *pv* is missing

Installing missing package pv

---

app/Dockerfile

Mattermost 5.19 was released today, bumping the Dockerfile ENV variable so Docker installs can upgrade.
N/A

bump to 5.19.0

---

db/Dockerfile

Closes #446 by adding libressl-dev into the apk packages being installed in the db container on build.
https://github.com/mattermost/mattermost-docker/issues/446

Add package libressl-dev to db/Dockerfile

---

web/mattermost-ssl

Removes the deprecated nginx directive `ssl` which causes a warning when starting `mattermost-docker`.
A replacement is not necessary, because the `ssl` flag is already set on the `listen` directive here:
https://github.com/mattermost/mattermost-docker/blob/492ecd5ca3c761e309834ba0389dd13e7bc431d4/web/mattermost-ssl#L13
Fixes #451.

Removes the deprecated nginx ssl directive (#451)

---

web/entrypoint.sh

When trying to enable SSL, I added the certificate as described here: https://github.com/mattermost/mattermost-docker#install-with-ssl-certificate
However, the web server was still listenting to port 80 instead of port 443 and it took me a moment to see why. The startup output of docker-compose contains this:
```
web_1  | ln: /etc/nginx/conf.d/mattermost.conf: File exists
web_1  | found certificate and key, linking ssl config
```
While the second line suggests, that the config *mattermost-ssl* is being used, the first line tells us, that the linking was not successful, because the symlink already exists from a previous execution. The existing link can be overwritten by adding `-f --force` to `ln`.
Related: mattermost#366 (mattermost#366 would probably need to be updated with the same …

web entrypoint: forcefully link existing config

---

docker-compose.yml

I could not find any use of `MATTERMOST_ENABLE_SSL`. It's therefore only confusing to have it in the docker-compose as an apparent configuration flag.
This PR is obsolete should https://github.com/mattermost/mattermost-docker/pull/366 be accepted.

Remove unused ENV variable from docker-compose

---

web/entrypoint.sh

In this commit I'm adding some logic to ensure that the `entrypoint.sh`
file handles a pre-existing `mattermost.conf` file within the nginx
folder.
During deployment of some more custom nginx configuration it was
noticed that the linking process fails, because a file already exists
with the filesystem.
Signed-off-by: Akendo <akendo@akendo.eu>

Fix the linking of the nginx configuration file

---

db/Dockerfile

Currently the command `docker-compose build` throws an error for building the database because it uses an old pip version.
This PR updates pip right before it is called. Anyways this should just be a temporary fix because the image uses Python 2.7 wich out of support since Jan 2020
Fixes: https://github.com/mattermost/mattermost-docker/issues/469

[GH-469] Fixing docker-compose build process

---

README.md
docker-compose.yml

This pull request is to fix certificate signed by unknown authority when you want to use SSO from GitLab with selfsigned certificate that are not known by Alpine in the app container.
Fixes https://github.com/mattermost/mattermost-server/issues/13059

Fix : certificate signed by unknown authority

---

app/Dockerfile

Right now, multiple sources point to the server binaries on releases.mattermost.com, including the download page, upgrade instructions, Helm charts, version archive, and others.
We can identify the download source by adding a querystring to the url, i.e. https://releases.mattermost.com/5.22.1/mattermost-5.22.1-linux-amd64.tar.gz?src=docker-app
The intent is that we can then identify sources of downloads, identify those that typically lead to an unsuccessful server activation, and improve the experience for the developer/administrator.
This PR adds the "?src=docker-app" querysting tag to download source for the Docker app, so we know when someone downloaded it from this source
See https://github.com/mattermost/docs/pull/3596 for a similar change made to download sources on the version …

Add ?src=docker-app query parameter to identify download source

---

.travis.yml

Remove 'sudo: required' as it is now  deprecated per the documentation:
https://changelog.travis-ci.com/the-container-based-build-environment-is-fully-deprecated-84517
Fixes https://github.com/mattermost/mattermost-docker/issues/470

Remove sudo: required as it is deprecated.

---

web/mattermost-ssl

Add TLS 1.3 support to nginx web server. 
Thanks, Jacobo

add TLS 1.3 support to web container

---

app/entrypoint.sh

Cleanup of docker startup script for mattermost application
- quote arguments to avoid globbing and word splitting
- uniform format for if-then-else

Cleanup of docker startup script for mattermost application

---

app/Dockerfile

Sets an environment variable to get an idea of the preferred installation type.  
https://mattermost.atlassian.net/browse/DOPS-215

DOPS-215: Add MM_INSTALL_TYPE=docker environment variable.

---

web/mattermost-ssl

This PR updates the supported ciphers and TLS versions in the nginx SSL config. TLS versions 1.0 and 1.1 are no longer supported by any browser and are considered deprecated. Comparing [client software versions](https://docs.mattermost.com/install/requirements.html#client-software) with [this table of which browsers support TLS 1.2](https://caniuse.com/tls1-2), all Mattermost supported browsers also support TLS 1.2, so we can safely remove TLS 1.0 and 1.1 without impacting many users. The biggest group of affected users would be IE10 users, but IE10 was end of life in January so those users should have moved on by now. Not sure which version of chrome is shipped with the mattermost client, but I am assuming it's not from 2013 so it should support TLS1.2 as well.
With TLS 1.0 and 1.1 …

Update SSL ciphers and TLS versions in nginx config file

---

MAINTENANCE.md
README.md
app/entrypoint.sh
db/entrypoint.sh
db/setup-wale.sh
web/entrypoint.sh

Changed shell script format to better match [Google Bash Style Guide](https://google.github.io/styleguide/shellguide.html). Mainly changed tabs to two spaces; also corrected two misspelled words within Markdown documents.
This PR is not related to an issue/ticket

Updating shell scripts to adhear better to Bash style guides

---

app/Dockerfile
docker-compose.yml

To easily specify the desired MM version
fixes #499

Make MM_VERSION an ARG instead of an ENV

---

docker-compose.yml
web/Dockerfile
web/mattermost
web/mattermost-ssl

**Hardening for production environments.**
According to ['OWASP Docker Security Cheat Sheet'](https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html) Docker container should be configured with unprivileged user. In addition nginx container is hardened by dropping all capabilities. `The most secure setup is to drop all capabilities --cap-drop all`
Changes:
- Official nginxinc unprivileged container `nginx:mainline-alpine` -> `nginxinc/nginx-unprivileged:mainline-alpine` 
- Required changes from [nginxinc/nginx-unprivileged](https://github.com/nginxinc/docker-nginx-unprivileged)
> *   The default NGINX listen port is now `8080` instead of `80`.
> *   The default NGINX user directive in `/etc/nginx/nginx.conf` has been removed.
> *   The default NGINX PID has been …

Hardening: Change nginx container to unprivileged

---

db/Dockerfile

- upgrade python-dev to python3-dev since python2 is no longer available
- py-pi to pi3-pip
fixes #528 #489 
For anybody in need and avoiding the complexity, you can use the DB images from
https://hub.docker.com/repository/docker/eugenmayer/mattermost-db
build by https://github.com/EugenMayer/mattermost-boilerplate - you will find versions prior 5.33.0 based on pg 9.6 and versions above base on pg 10. 
Those images are unmodified variants of this repo - just publish to docker-hub for obvious convenience reasons i guess :)

Upgrade Postgres to 10 for 5.33.0
