app/config.template.json, app/docker-entry.sh, db/make_db.sh
Those parameters can be configured through environment variables now.
=> Allow db host, name user and password to be configurable

README.md, db/Dockerfile, db/docker-entrypoint1.sh, db/setup-wale.sh, docker-compose-nossl.yml, docker-compose-ssl.yml
=> Enable database backup through Wal-E

db/docker-entrypoint1.sh
WAL logs in archive mode will consume a lot more spaces and not useful
when backup is off. This fix add ability to switch WAL logs mode based
on the backup switch.
=> Fix #15, WAL in archive mode when backup is off

db/docker-entrypoint1.sh, db/setup-wale.sh
This is related to https://github.com/mattermost/mattermost-docker/issues/46
=> Add environment var to allow customize archive timeout

README.md
=> Update link to install guide

MAINTENANCE.md, README.md
Drafting maintenance info page to serve as a template for other open source projects to recognize maintainers
=> Maintainer Guide

docker-compose-v1.yml, docker-compose.yml
setting `restart` to `always` makes it impossible to stop a service
=> services should be stoppable

app/Dockerfile, app/Dockerfile-enterprise
Upgrade to Mattermost 3.8.2 which fix websockets issue.
Changelog [here](https://docs.mattermost.com/administration/changelog.html#release-v3-8-2)
Fix #120
=> Upgrade to Mattermost 3.8.2

app/Dockerfile, app/Dockerfile-enterprise
Upgrade to Mattermost 3.9.0
Changelog [here](https://docs.mattermost.com/administration/changelog.html#release-v3-9-0)
=> Upgrade to Mattermost 3.9.0

MAINTENANCE.md
Hi @xcompass !
If you're interesting in some help to maintain this project, I'll be happy to participate.
=> Do you want any help ?

web/mattermost, web/mattermost-ssl
On the [Compatibility > Breaking changes](https://docs.mattermost.com/administration/changelog.html#compatibility) section, they asked us to replace one line in the NGINX file, according to [documentation](https://docs.mattermost.com/install/install-ubuntu-1404.html#configuring-nginx-as-a-proxy-for-mattermost-server).
I updated the whole file to be more similar with the documentation.
**Please, pay special attention to the SSL version of the NGINX file, since I'm not familiar with SSL configs on NGINX, so it's more susceptible to contain errors.**
=> Follows the NGINX Breaking Changes suggestion

app/docker-entry.sh
In PR #31, @pierreozoux proposed an elegant way to not use hardcoded salts in app container. I propose to merge this to master.
(cc @MichaelEischer who also ask for this change)
=> Do not use hardcoded value for salts 

app/Dockerfile, app/Dockerfile-enterprise
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-0-0)
Seems there is no important changes for us and web image is already ready to support APIv4.
=> Update to 4.0.0

app/Dockerfile, app/Dockerfile-enterprise
Mattermost released a patch version of version `4.0`
Changelog [here](https://docs.mattermost.com/administration/changelog.html#release-v4-0-1)
=> Upgrade to 4.0.1

web/mattermost-ssl
As suggested by @pichouk here: https://github.com/mattermost/mattermost-docker/issues/156#issuecomment-316475874
=> Add 301 redirect from port 80 to port 443

app/Dockerfile, app/Dockerfile-enterprise
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-0-2)
=> Upgrade to 4.0.2

app/Dockerfile, app/Dockerfile-enterprise
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-0-3).
=> Upgrade mattermost to 4.0.3

app/Dockerfile, app/Dockerfile-enterprise
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-1-0)
=> Upgrade to 4.1.0

app/Dockerfile, app/Dockerfile-enterprise
Released now: https://github.com/mattermost/mattermost-server/releases/tag/v4.2.0
=> Upgrade to mattermost 4.2

docker-compose.yml
Added commented section for enabling SSL
=> Added SSL example

app/docker-entry.sh
I've got bug from docker-compose when I started it. I've just added space
=> Bash if statement [: missing `]' error 54 line

app/entrypoint.sh
Few comments, no needs to review.
=> Comment and indent app entrypoint

app/Dockerfile
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-3-1).
=> Upgrade to 4.3.1

app/Dockerfile
Here is the changelog: https://docs.mattermost.com/administration/changelog.html#release-v4-2-1
=> Release 4.2.1

app/Dockerfile
Here is the change log: https://docs.mattermost.com/administration/changelog.html#release-v4-1-2
=> Release 4.1.2

web/Dockerfile, web/entrypoint.sh
As suggest on PR#135 I propose to use Alpine based Nginx image for Web container.
I just test it and the image size went from 108MB to 15.5MB :)
=> Use Alpine based Nginx image for Web container

app/Dockerfile
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-4-3)
=> Upgrade to 4.4.3

app/Dockerfile
Changelog is [here](https://docs.mattermost.com/administration/changelog.html?highlight=changelog#release-v4-4-5)
=> Upgrade to 4.4.5

app/Dockerfile
Changelog [here](https://docs.mattermost.com/administration/changelog.html?highlight=changelog#release-v4-5)
=> Upgrade mattermost to 4.5.0

app/Dockerfile
Fix #217 with the default configuration on the PluginSettings as they use relative paths.
=> Change the working dir for plugins to work

app/Dockerfile
See https://github.com/mattermost/mattermost-docker/issues/225
=> Add xmlsec1 package

app/Dockerfile
=> Add mime-support to get /etc/mime.types file

app/Dockerfile
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-7)
=> Upgrade to 4.7.2

app/Dockerfile
Fix a moderate security issue.
=> Upgrade to 4.7.3

web/mattermost-ssl
Some improvements proposal from @cht47 on #242.
I'll appreciate review since I'm not an expert with TLS recommendations :)
=> Improve TLS security

web/mattermost-ssl
Reverts mattermost/mattermost-docker#243
=> Revert "Improve TLS security"

app/Dockerfile
Changelog: https://github.com/mattermost/docs/blob/v4.8-documentation/source/administration/changelog.md#release-v48
=> Upgrade mattermost to v4.8.0

app/Dockerfile
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-9)
=> Upgrade to 4.9.1

app/Dockerfile
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v4-9)
=> Upgrade to 4.9.2

app/Dockerfile
Changelog is : https://docs.mattermost.com/administration/changelog.html#release-v4-10
=> Upgrade 4.10.1

app/Dockerfile, app/entrypoint.sh
Changelog: https://docs.mattermost.com/administration/changelog.html#release-v5-0
=> Upgrade to mattermost 5.0.0

app/Dockerfile
Changelog: https://docs.mattermost.com/administration/changelog.html#release-v5-1
=> Upgrade to 5.1.0

app/Dockerfile
Changelog: https://docs.mattermost.com/administration/changelog.html#release-v5-2
=> Upgrade to MM 5.2.0

app/Dockerfile
```
$ docker image list
REPOSITORY                                                   TAG                 IMAGE ID            CREATED              SIZE
mattermost-vanilla                                           latest              a866906c3a0f        29 seconds ago       296MB
mattermost-optimized                                         latest              ef0496e21f71        About a minute ago   156MB
```
=> Collapsing RUNs to save space by combining layers

app/Dockerfile
=> Use latest alpine image for app container

app/Dockerfile
Changelog is [here](https://docs.mattermost.com/administration/changelog.html#release-v5-4)
=> Upgrade to 5.4.0

db/Dockerfile
=> Fix database HEALTHCHECK with correct user/db name

app/entrypoint.sh, contrib/kubernetes/mattermost.deployment.yaml
Hello,
I have corrected the typo and UUOC(Useless Use of Cat) problem.
Thanks.
=> fix uuoc and typo

db/Dockerfile, db/setup-wale.sh
I made some simple adjustments so that wal-e can be reused. Check Please.
=> fix S3 wal-e support

app/Dockerfile, contrib/aws/Dockerrun.aws.json, contrib/kubernetes/mattermost.deployment.yaml, contrib/swarm/docker-stack-traefik.yml, contrib/swarm/docker-stack.yml
=> update MM to 5.7.2

app/Dockerfile, contrib/aws/Dockerrun.aws.json, contrib/kubernetes/mattermost.deployment.yaml, contrib/swarm/docker-stack-traefik.yml, contrib/swarm/docker-stack.yml
=> update MM to 5.8.0

app/Dockerfile
=> Upgrade alpine to 3.9

app/Dockerfile, contrib/aws/Dockerrun.aws.json, contrib/kubernetes/mattermost.deployment.yaml, contrib/swarm/docker-stack-traefik.yml, contrib/swarm/docker-stack.yml
=> bump to use 5.9.0

README.md
Reverts mattermost/mattermost-docker#388
=> Revert "update readme to add deprecation notice"

contrib/kubernetes/README.md, contrib/kubernetes/mattermost.deployment.yaml, contrib/kubernetes/mattermost.svc.yaml
Fixes some errors in the kubernetes manifests and bumps the version to 5.14.1
=> Kubernetes Fixes

docker-compose.yml
currently, if you follow the instructions and uncomment the lines, you
will get a YAML error:
```
ERROR: yaml.parser.ParserError: while parsing a block mapping
in "./docker-compose.yml", line 23, column 5
expected <block end>, but found '<block mapping start>'
in "./docker-compose.yml", line 25, column 7
```
found the potential solution in mattermost/mattermost-docker#343
=> allow uncommenting for team edition

app/Dockerfile
=> Update to 5.22.0

app/Dockerfile, app/entrypoint.sh
As mentioned [here](https://github.com/mattermost/mattermost-docker/pull/492#issuecomment-721864183) this PR will make `entrypoint.sh` and `Dockerfile` more consistent.
=> Consistency of app/*

app/Dockerfile, db/Dockerfile
Currently `docker-compose build` is failing, this MR will fix that issue and also default version of MM is outdated, I've set it to `5.36.0`.
Fixes https://github.com/mattermost/mattermost-docker/issues/542
=> Fixed build issue and upgraded MM_VERSION
